
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Matches users with suitable MFI institutions based on loan application details.
 *
 * - matchMfiInstitutions - A function that matches users with MFI institutions.
 * - MfiMatchingInput - The input type for the matchMfiInstitutions function.
 * - MfiMatchingOutput - The return type for the matchMfiInstitutions function.
 * - MfiInstitution - The type for a single MFI institution.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const MfiMatchingInputSchema = z.object({
  logbookDetails: z
    .string()
    .describe('Details of the logbook being used as collateral.'),
  nationalId: z.string().describe('National ID number of the loan applicant.'),
  loanAmount: z.number().describe('The amount of loan requested by the applicant.'),
  creditScore: z.number().optional().describe('The credit score of the loan applicant, if available (0-1000). Defaults to 0 if not provided.'),
  employmentStatus: z.string().describe('Employment status of the loan applicant.'),
  location: z.string().describe('The location of the loan applicant.'),
});
export type MfiMatchingInput = z.infer<typeof MfiMatchingInputSchema>;

const MfiInstitutionSchema = z.object({
  name: z.string().describe('Name of the MFI institution.'),
  interestRate: z.number().describe('Interest rate offered by the MFI institution (as a percentage, e.g., 13.5 for 13.5%).'),
  processingTime: z.string().describe('Typical loan processing time.'),
  requirements: z.array(z.string()).describe('List of requirements for loan application.'),
  contactInformation: z.string().describe('Contact details for the MFI institution (phone or general inquiry).'),
  approvalRate: z.number().describe('Historical loan approval rate as a decimal (e.g., 0.85 for 85%).'),
  loanTerms: z.string().describe('Summary of key loan terms and conditions (e.g., "Max loan tenure 24 months", "Logbook must be for vehicle not older than 10 years").'),
  websiteUrl: z.string().optional().describe('Official website URL of the MFI.'),
  applicationUrl: z.string().optional().describe('Direct URL to the MFI loan application page, if available.'),
});
export type MfiInstitution = z.infer<typeof MfiInstitutionSchema>;

const MfiMatchingOutputSchema = z.array(MfiInstitutionSchema).describe('A list of suitable MFI institutions.');
export type MfiMatchingOutput = z.infer<typeof MfiMatchingOutputSchema>;

export async function matchMfiInstitutions(input: MfiMatchingInput): Promise<MfiMatchingOutput> {
  return matchMfiInstitutionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'mfiMatchingPrompt',
  model: 'googleai/gemini-2.0-flash', // Explicitly define the model
  input: {
    schema: MfiMatchingInputSchema,
  },
  output: {
    schema: MfiMatchingOutputSchema,
  },
  prompt: `You are an expert financial advisor specializing in logbook loans in Kenya. Based on the loan application details, identify the 5 most suitable Kenyan MFI institutions.

Consider factors such as loan amount, applicant's logbook details, credit score (assume 0 or low if not explicitly high), employment status, and location, as well as the MFI's interest rates, processing times, requirements, website URLs, and application URLs. Use the example MFIs below as a guide for the kind of information and format to return. Do NOT limit your suggestions to only these examples; find real and applicable MFIs based on the applicant's profile.

Example Kenyan MFIs:
\`\`\`
[
  {
    "name": "Faulu Kenya",
    "interestRate": 13.5,
    "processingTime": "24-48 hours",
    "requirements": ["Original Logbook", "National ID", "KRA PIN", "6 months M-Pesa/Bank Statement", "Comprehensive Insurance"],
    "contactInformation": "0711074000 / 0709700000",
    "approvalRate": 0.80,
    "loanTerms": "Loan amounts up to 70% of vehicle value. Vehicle must be less than 15 years old.",
    "websiteUrl": "https://www.faulukenya.com",
    "applicationUrl": "https://www.faulukenya.com/logbook-loans"
  },
  {
    "name": "Platinum Credit Kenya",
    "interestRate": 15.0,
    "processingTime": "Within 24 hours",
    "requirements": ["Original Logbook", "National ID", "KRA PIN", "Utility Bill", "Bank Statements"],
    "contactInformation": "0709900000",
    "approvalRate": 0.85,
    "loanTerms": "Flexible repayment periods up to 36 months. No CRB check for some products.",
    "websiteUrl": "https://platinumcredit.co.ke",
    "applicationUrl": "https://platinumcredit.co.ke/apply-now"
  },
  {
    "name": "Momentum Credit",
    "interestRate": 14.0,
    "processingTime": "As fast as 1 hour",
    "requirements": ["Original Logbook", "National ID", "KRA PIN", "Proof of Income"],
    "contactInformation": "0709434000",
    "approvalRate": 0.78,
    "loanTerms": "Financing up to KES 3 million. Insurance financing available.",
    "websiteUrl": "https://momentumcredit.co.ke",
    "applicationUrl": "https://momentumcredit.co.ke/logbook-loans-application"
  },
  {
    "name": "Jijenge Credit",
    "interestRate": 16.0,
    "processingTime": "Same day processing",
    "requirements": ["Original Logbook", "National ID", "KRA PIN", "Two passport photos"],
    "contactInformation": "0711280000",
    "approvalRate": 0.75,
    "loanTerms": "Loans from KES 50,000. Repayment period up to 12 months.",
    "websiteUrl": "https://jijengecredit.com",
    "applicationUrl": "https://jijengecredit.com/application"
  },
  {
    "name": "Izwe Kenya",
    "interestRate": 14.5,
    "processingTime": "24-72 hours",
    "requirements": ["Original Logbook", "National ID", "KRA PIN", "Bank Statements", "Proof of Residence"],
    "contactInformation": "0207602000",
    "approvalRate": 0.79,
    "loanTerms": "Loans up to KES 2.5 million. Repayment up to 24 months.",
    "websiteUrl": "https://www.izwekenya.com",
    "applicationUrl": "https://www.izwekenya.com/apply"
  }
]
\`\`\`

Applicant Details:
- Logbook Details: {{{logbookDetails}}}
- National ID: {{{nationalId}}}
- Loan Amount: {{{loanAmount}}}
- Credit Score: {{{creditScore}}}
- Employment Status: {{{employmentStatus}}}
- Location: {{{location}}}

Return a JSON array of 5 suitable Kenyan MFI institutions, formatted as in the examples above. Ensure all fields, including websiteUrl and applicationUrl (if available, otherwise omit them or provide a general link), are populated.
`,
});

const matchMfiInstitutionsFlow = ai.defineFlow(
  {
    name: 'matchMfiInstitutionsFlow',
    inputSchema: MfiMatchingInputSchema,
    outputSchema: MfiMatchingOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

